server:
  port: 8081

spring:
  application:
    name: room-service

chess-command:
  address: ~
  initRoomEndpoint: /api/board
  deleteRoomEndpoint: /api/board

kafka:
  bootstrapAddress: ~
  partitionsPerTopic: 1
  replicationFactor: 1

logging:
  level:
    org.apache.kafka: WARN