name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout branch
      uses: actions/checkout@v3
      
    - name: Step 2 - Install Java 11
      uses: actions/setup-java@v1
      with:
        java-version: "11"
        
    - name: Step 3 - Build project
      run: mvn -B package --file pom.xml
          
    - name: Step 4 - Login to Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Step 5 - Build the Docker image
      run: docker build . --file Dockerfile --tag qsspy/distributed-chess-room-service:latest
      
    - name: Step 6 - Push to Docker Hub
      run: docker push qsspy/distributed-chess-room-service
